title = "Sift"
gitSourceBranch = "main"

classOrder = ["Sift"]

[home]
includeReadme = true

[[navbar.items]]
label = "Sponsor"
href = "https://github.com/sponsors/csqrl"
position = "right"

[docusaurus.themeConfig.colorMode]
respectPrefersColorScheme = true
defaultMode = "dark"
