[package]
name = "csqrl/sift"
version = "0.1.0"

description = """
Immutable data library for Luau and Roblox.

Documentation: <https://cxmeel.github.io/sift>"""

registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
