name: deploy-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "moonwave.toml"
      - "**/*.md"

jobs:
  deploy:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Moonwave
        run: npm install -g moonwave

      - name: Setup Git
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docs
        run: moonwave build --publish
